global:
  LogLevel: info

db:
  Path: ./data/db
  Type: badger-db

ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

TcpPort:
UdpPort:

bootnode:
  ExternalIP:
  PrivateKey:
