global:
  LogLevel: info

db:
  Path: ./data/db
  Type: badger-db

ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s
  OperatorPrivKey:

BeaconNodeAddr: eth2-4000-prysm-ext.stage.bloxinfra.com:80
HostAddress: example.ip
TcpPort:
UdpPort:

bootnode:
  ExternalIP:
  PrivateKey:
